###########
# site.title

title:    'MetroAI'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

markdown: kramdown
kramdown:
  input: GFM

exclude:
- README.md
- LICENSE.md
